title:        clj-fuzzy
tagline:      'clj-fuzzy'
description:  'A handy collection of algorithms dealing with fuzzy strings and phonetics.'
baseurl:      /clj-fuzzy
version:      0.1.7
author:
  name:       'Yomguithereal'
markdown:     redcarpet
pygments:     true
paginate:     5
