# Metadata
title: clj-fuzzy
tagline: clj-fuzzy
description: 'A handy collection of algorithms dealing with fuzzy strings and phonetics.'
baseurl: /clj-fuzzy
version:      0.3.3
author:
  name:       'Yomguithereal'

# Configuration
highlighter: rouge
markdown: kramdown
