title:        clj-fuzzy
tagline:      'clj-fuzzy'
description:  'A handy collection of algorithms dealing with fuzzy strings and phonetics.'
url:          yomguithereal.github.io/clj-fuzzy
baseUrl:      /
version:      0.1.7
author:
  name:       'Yomguithereal'
markdown:     redcarpet
pygments:     true
paginate:     5
